owner: novatorsoft
repo: upptime

sites:
  - name: "Novatorsoft Website"
    url: https://novatorsoft.com/

  - name: "Novatorsoft CMS"
    url: $NOVATORSOFT_CMS_URL

  - name: "Novatorsoft OS"
    url: $NOVATORSOFT_OS_URL

  - name: "Novatorsoft Plane"
    url: $NOVATORSOFT_PLANE_URL

  - name: "Novatorsoft Kimai"
    url: $NOVATORSOFT_KIMAI_URL

  - name: "IK Website"
    url: https://ismetkizgin.com/

  - name: "IK CV"
    url: https://cv.ismetkizgin.com.tr

  - name: "IK Admin"
    url: $IK_ADMIN_URL

  - name: "IK API"
    url: $IK_API_URL

  - name: "IK Export Service"
    url: $IK_EXPORT_SERVICE_URL
    expectedStatusCodes:
      - 403

  - name: "IK Search Service"
    url: $IK_SEARCH_SERVICE_URL
    expectedStatusCodes:
      - 403

  - name: "IK Redirect Service"
    url: $IK_REDIRECT_SERVICE_URL

  - name: "IK Sentiment Analysis Service"
    url: $IK_SENTIMENT_ANALYSIS_SERVICE
    expectedStatusCodes:
      - 403

  - name: "IK Services"
    url: $IK_SERVICES_URL
    expectedStatusCodes:
      - 403

  - name: "Cihat Kılıç Pilates Studio"
    url: https://cihatkilicpilatesstudio.com/

status-website:
  baseUrl: /upptime
  logoUrl: https://icons.duckduckgo.com/ip3/novatorsoft.com.ico
  favicon: https://icons.duckduckgo.com/ip3/novatorsoft.com.ico
  name: Novatorsoft
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/novatorsoft/upptime
