owner: novatorsoft
repo: upptime

sites:
  - name: "Novatorsoft Website"
    url: https://novatorsoft.com/

status-website:
  baseUrl: /
  logoUrl: https://icons.duckduckgo.com/ip3/novatorsoft.com.ico
  favicon: https://icons.duckduckgo.com/ip3/novatorsoft.com.ico
  name: Novatorsoft
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/novatorsoft/upptime
